name: Deploy to Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: netlify-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy to Netlify (prod)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy             --prod             --dir=dist             --site="$NETLIFY_SITE_ID"
